### ISSUE TITLE
DeepCut with TF2?

### ISSUE THREAD

**Issue by oleang** [rkcosmos/deepcut#58]
Can the DeepCut now work with TensorFlow 2?

**Comment by titipata** [comment]
We haven't re-trained model in TF2 yet. I'll see if anyone can make it available soon.

**Comment by titipata** [comment]
@kittinan, @heytitle, @rkcosmos Should we refactor the code so that it works with recent `TensorFlow ` 2.0?

**Comment by kittinan** [comment]
The solution may be on this issue https://github.com/keras-team/keras/issues/12379#issuecomment-471339468

Error log Deepcut Tensorflow 2.0 Colab

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in _get_default_graph()
     65     try:
---> 66         return tf.get_default_graph()
     67     except AttributeError:

AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
8 frames
/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in _get_default_graph()
     67     except AttributeError:
     68         raise RuntimeError(
---> 69             'It looks like you are trying to use '
     70             'a version of multi-backend Keras that '
     71             'does not support TensorFlow 2.0. We recommend '

RuntimeError: It looks like you are trying to use a version of multi-backend Keras that does not support TensorFlow 2.0. We recommend using `tf.keras`, or alternatively, downgrading to TensorFlow 1.14.
```

**Comment by rkcosmos** [comment]
I guess it is time for an update. I will try to look into it today.

**Comment by rkcosmos** [comment]
fixed with #63
